version: '3.5'

networks:
  lemp_net:
    name: lemp-net
    driver: bridge
    ipam:
     config:
       - subnet: 172.16.0.0/29

volumes:
  srcs_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/SHARED/IRC
    name: srcs_data

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: server
    image: server
    networks:
      lemp_net:
        ipv4_address: 172.16.0.2
    volumes:
      - type: volume
        source: srcs_data
        target: /srcs
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  client1:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: client1
    image: client
    networks:
      lemp_net:
        ipv4_address: 172.16.0.3
    volumes:
      - type: volume
        source: srcs_data
        target: /srcs
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  client2:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: client2
    image: client
    networks:
      lemp_net:
        ipv4_address: 172.16.0.4
    volumes:
      - type: volume
        source: srcs_data
        target: /srcs
    stdin_open: true # docker run -i
    tty: true        # docker run -t