version: '3'

networks:
  lemp_net:
services:
  #####################
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WP_ADMIN: ${WP_ADMIN}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_USER: ${WP_USER}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
    expose:
        - "3306"
    restart: always
    image: mariadb_img:1.0
    networks:
      - lemp_net
    volumes:
      - /home/${USER}/data/mariadb:/mariadb/
  #####################
  php-fpm:
    build: ./requirements/php-fpm/
    container_name: php-fpm
    depends_on:
      - mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}
    image: php-fpm_img:1.0
    networks:
      - lemp_net
    expose:
      - "9000"
    restart: always
    volumes:
      - /home/${USER}/data/wordpress:/var/www/html/
  #####################
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    volumes:
      - /home/${USER}/data/wordpress:/var/www/html/
    depends_on:
      - php-fpm
    image: nginx_img:1.0
    networks:
      - lemp_net
    ports:
      - "443:443"
    restart: always