version: '3'

services:
  #####################
  nginx:
    image: nginx_img:1.0
    build: ./requirements/nginx/
    ports:
      - 80:80
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: always
    volumes:
      # - wordpress_data:/var/www/html/
      - /home/${USER}/data/wordpress:/var/www/html/
    networks:
      - lemp_net
    # depends_on:
    #   - wordpress
  #####################
  # mariadb:
  #   image: mariadb_img:1.0
  #   build: ./requirements/mariadb/
  #   # ports:
  #   #   - "80:3386"
  #   stdin_open: true # docker run -i
  #   tty: true        # docker run -t
  #   restart: always
  #   volumes:
  #     # - mariadb_data:/srv/mariadb/
  #     - /home/${USER}/data/mariadb:/mariadb/
  #   networks:
  #     - lemp_net
  #####################
  wordpress:
    image: wordpress_img:1.0
    build: ./requirements/wordpress/
    # ports:
    #   - "80:9000"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: always
    volumes:
      # - wordpress_data:/var/www/html/wordpress/
      - /home/${USER}/data/wordpress:/var/www/html/
    depends_on:
      - nginx
    expose:
      - "9000"
    networks:
      - lemp_net
################################################
# volumes:
#   # mariadb_data:
#   #   external: false
#   # wordpress_data:
#   #   external: false
#   wordpress_data:
#       driver: local
#       driver_opts:
#           type: none
#           o: bind
#           device: "home/${USER}/data/wordpress/"
#   mariadb_data:
#     driver: local
#     driver_opts:
#         type: none
#         o: bind
#         device: "home/${USER}/data/mariadb/"
################################################
networks:
  lemp_net: