version: '3.5'

networks:
  lemp_net:
    name: lemp-net
    driver: bridge
    ipam:
     config:
       - subnet: 172.16.0.0/29

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/wordpress
    name: wordpress_data
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/mariadb
    name: mariadb_data

services:
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WP_ADMIN: ${WP_ADMIN}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_USER: ${WP_USER}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
    expose:
        - "3306"
    restart: always
    image: mariadb
    networks:
      lemp_net:
        ipv4_address: 172.16.0.2
    volumes:
      - type: volume
        source: mariadb_data
        target: /var/lib/mysql
  
  php-fpm:
    build: ./requirements/php-fpm/
    container_name: php-fpm
    depends_on:
      - mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}
    image: php-fpm
    networks:
      lemp_net:
        ipv4_address: 172.16.0.3
    expose:
      - "9000"
    restart: always
    volumes:
      - type: volume
        source: wordpress_data
        target: /var/www/html

  nginx:
    build:
      context: ./requirements/nginx/
      args:
        - NGINX_PRIVATE_CERT=${NGINX_PRIVATE_CERT}
    container_name: nginx
    volumes:
      - type: volume
        source: wordpress_data
        target: /var/www/html
    depends_on:
      - php-fpm
    image: nginx
    networks:
      lemp_net:
        ipv4_address: 172.16.0.4
    ports:
      - "443:443"
    restart: always

  adminer:
    build: ./requirements/adminer/
    container_name: adminer
    volumes:
      - type: volume
        source: wordpress_data
        target: /var/www/html
    depends_on:
      - php-fpm
    image: adminer
    networks:
      lemp_net:
        ipv4_address: 172.16.0.5

  vsftpd:
    build:
      context: ./requirements/vsftpd/
      args:
        - WP_ADMIN=${WP_ADMIN}
        - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
    container_name: vsftpd
    volumes:
      - type: volume
        source: wordpress_data
        target: /var/www/html
    depends_on:
      - php-fpm
    image: vsftpd
    networks:
      lemp_net:
        ipv4_address: 172.16.0.6
    ports:
      - "20:20"

#DEBUG
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t