version: '3'

services:
  #####################
  nginx:
    image: nginx_img:1.0
    build: ./requirements/nginx/
    ports:
      - "80:80"           #remove, anche nel Dockerfile
      - "443:443"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: always
    volumes:
      - wordpress_data:/srv/wordpress_data
    # depends_on:
    #   - mariadb
  #####################
  mariadb:
    image: mariadb_img:1.0
    build: ./requirements/mariadb/
    # ports:
    #   - "80:3386"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: always
    volumes:
      - mariadb_data:/srv/mariadb_data
  #####################
  wordpress:
    image: wordpress_img:1.0
    build: ./requirements/wordpress/
    # ports:
    #   - "80:9000"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: always
    volumes:
      - wordpress_data:/srv/wordpress_data
################################################
volumes:
  mariadb_data:
    external: false
  wordpress_data:
    external: false
